# # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# # More GitHub Actions for Azure: https://github.com/Azure/actions

# .github/workflows/azure-webapps-node.yml
name: Build and deploy Node.js app to Azure Web App - textsimplification12

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install server deps (root)
        run: npm ci

      # If your server builds/serves the React bundle from client/build,
      # explicitly build the client here
      - name: Install client deps
        run: npm ci
        working-directory: client

      - name: Build client (disable CRA CI warnings-as-errors)
        run: npm run build
        working-directory: client
        env:
          CI: ""   # <- make CRA treat warnings as warnings, not errors

      # Optional: sanity print of built files
      - name: List client build contents
        run: ls -la client/build || ls -la client/dist

      # Upload everything (server + built client) as artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B20F2F0C58584DA4807A33DDFF0AF1A7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3B6C0091868E49EA97B89B691B49887D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B02686DE65764FB6B90683561825E1DA }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'textsimplification12'
          slot-name: 'Production'
          package: .
# name: Build and deploy Node.js app to Azure Web App - textsimplification12

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read #This is required for actions/checkout

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Node.js version
#         uses: actions/setup-node@v3
#         with:
#           node-version: '22.x'

#       - name: npm install, build, and test
#         run: |
#           npm install
#           npm run build --if-present
#           npm run test --if-present

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v4
#         with:
#           name: node-app
#           path: .

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     permissions:
#       id-token: write #This is required for requesting the JWT
#       contents: read #This is required for actions/checkout

#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v4
#         with:
#           name: node-app
      
#       - name: Login to Azure
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B20F2F0C58584DA4807A33DDFF0AF1A7 }}
#           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3B6C0091868E49EA97B89B691B49887D }}
#           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B02686DE65764FB6B90683561825E1DA }}

#       - name: 'Deploy to Azure Web App'
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v3
#         with:
#           app-name: 'textsimplification12'
#           slot-name: 'Production'
#           package: .

          
